version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: bigtool-redis
    ports:
      - "6379:6379"
      - "8002:8001"  # RedisInsight web UI
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    driver: local